name: 'Terraform CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: terraform-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform-ci:
    name: 'Terraform Fmt, Validate & Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura credenziali AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-1

      - name: Create Kubernetes KinD Cluster
        uses: helm/kind-action@v1.12.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Controllo Formattazione (fmt)
        working-directory: environments/dev
        run: terraform fmt -check

      - name: Validazione Codice (validate)
        working-directory: environments/dev
        run: terraform validate
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_admin_cidr: ${{ secrets.TF_VAR_ADMIN_CIDR }}

      - name: Anteprima Modifiche (plan)
        working-directory: environments/dev
        run: terraform plan -no-color -input=false -lock=false
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_admin_cidr: ${{ secrets.TF_VAR_ADMIN_CIDR }}